export interface Card {
  title: string;
  description: string;
  longDescription: string;
  image: string;
  year: number;

  technologies: string[];
  tags: string[];
  githubLink?: string;
  website?: string;
  role?: string;
  duration?: string;
}

export const cards: Card[] = [
  //2025
  {
    title: 'Allergenics V2',
    description: 'Current W.I.P. Complete rework from the ground-up. Changed codebase to Next.js from base React, introduced Tailwind, adding A.I. model to backend.',
    longDescription: 'Allergenics V2 is a complete overhaul of the original senior project. The goal is to create a more robust and scalable application by migrating to Next.js for server-side rendering and improved performance. We are also integrating a custom-trained AI model to provide more accurate and personalized allergy warnings. The user interface is being redesigned with Tailwind CSS for a modern and responsive experience.',
    image:'/Projects/2025_allergenics.png',
    year: 2025,
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'PostCSS', 'Typescript', 'Python', 'Flask'],
    tags: ['Web App', 'AI/ML', 'Full-Stack'],
    githubLink: '',
    website: '',
    role: 'Lead Developer',
    duration: 'Ongoing',
  },
  {
    title: 'Banking Application',
    description: 'Participated in brief trial with a startup in NYC. Tasked with building a banking application from scratch. Built on Python, React, PostgreSQL, Grafana, Prometheus, Tempo, and ran through Docker build. One of the most valuable parts of this project was designing the backend to handle both ORM and raw SQL operations.',
    longDescription: 'As part of a trial with a New York-based fintech startup, I was tasked with developing a full-stack banking application. The backend was built with Python and FastAPI, utilizing both an ORM and raw SQL for optimized database interactions with PostgreSQL. The frontend was developed using React. Observability was a key focus, with Grafana, Prometheus, and Tempo integrated for monitoring. The entire application was containerized using Docker for easy deployment and scalability.',
    image: '/Projects/2025_banking_application.png',
    year: 2025,
    technologies: ['Python', 'React', 'PostgreSQL', 'Docker', 'Grafana', 'Prometheus'],
    tags: ['Fintech', 'Full-Stack', 'Contract'],
    githubLink: '',
    role: 'Gen AI Engineer (Trial Contract)',
    duration: 'Feb 2025 - March 2025',
  },
  //2024
  {
    title: 'Stevens Institute of Technology',
    description: 'Masters of Engineering in Applied Artificial Intelligence',
    longDescription: 'Completed a Master\'s of Engineering with a specialization in Applied Artificial Intelligence. Coursework focused on machine learning, deep learning, natural language processing, and computer vision. Gained hands-on experience in developing and deploying AI models for real-world applications.',
    image:'/Projects/2024_soccer.jpg',
    year: 2024,
    technologies: ['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn'],
    tags: ['Education', 'AI/ML'],
    githubLink: '',
    role: 'Student',
    duration: 'Sep 2023 - May 2024',
  },
  {
    title: 'youngcla.us',
    description: 'My new creative outlet.',
    longDescription: 'This portfolio website itself is a project that I actively maintain. It is built with Next.js and styled-components, and it serves as a playground for me to experiment with new web development technologies and design concepts. The goal is to create a visually appealing and interactive experience to showcase my work.',
    image:'/Projects/2024_website.png',
    year: 2024,
    technologies: ['React', 'Next.js', 'styled-components', 'TypeScript'],
    tags: ['Portfolio', 'Web Dev'],
    githubLink: 'https://github.com/youngclaus/weidenfeller',
    website: 'https://youngcla.us',
    role: 'Developer',
    duration: 'Actively Maintained',
  },
  //2023
  {
    title: 'Stevens Institute of Technology',
    description: 'B.E. Computer Engineering',
    longDescription: 'Graduated with a Bachelor\'s of Engineering in Computer Engineering. The curriculum provided a strong foundation in computer science, software development, and hardware design. Key areas of study included data structures, algorithms, operating systems, and computer architecture.',
    image: '/Projects/2019_stevens.jpg',
    year: 2023,
    technologies: ['C++', 'Java', 'Python', 'Verilog'],
    tags: ['Education', 'Computer Engineering'],
    githubLink: '',
    role: 'Student',
    duration: 'Sep 2019 - May 2023',
  },
  {
    title: 'Allergenics V1',
    description: 'My Senior Project. A website that automatically finds the menus of the nearest 20 food vendors near the user, and highlights dishes that could potentially contain something the user is allergic to. Time constraints forced my team to take a hit to front-end design to ensure the product worked for the Stevens Design Expo.',
    longDescription: 'For my senior design project, my team and I developed Allergenics, a web application designed to help users with food allergies dine out safely. The application scrapes menu data from nearby restaurants and uses a database of common allergens to flag potentially unsafe dishes. While we had to prioritize functionality over a polished UI due to time constraints, the project was a success at the Stevens Design Expo and demonstrated our ability to build a functional and useful product.',
    image:'/Projects/2023_allergenics.png',
    year: 2023,
    technologies: ['React', 'Node.js', 'Express', 'MongoDB'],
    tags: ['Web App', 'Health', 'Team Project'],
    githubLink: '',
    role: 'Frontend Developer',
    duration: 'Sep 2022 - May 2023',
  },
  {
    title: 'Stevens Design Expo',
    description: 'Great success at the Design Expo. Industry leaders, company reps, and family of students were inputting their own allergies and successfully seeing results for places near the Stevens campus.',
    longDescription: 'Presenting Allergenics at the Stevens Design Expo was a highlight of my undergraduate career. We received positive feedback from industry professionals and faculty on the concept and execution of the project. It was rewarding to see real users interact with our application and validate the need for such a tool.',
    image:'/Projects/2023_allergenics.jpg',
    year: 2023,
    technologies: [],
    tags: ['Presentation', 'Expo'],
    githubLink: '',
    role: 'Presenter',
    duration: 'May 2023',
  },
  //2022
  {
    title: 'Image Deconstruction',
    description: 'Done with Matlab. Introduction to what I would be doing post-grad.',
    longDescription: 'This project was an introduction to image processing using Matlab. I learned how to manipulate images, apply filters, and extract features. This experience sparked my interest in computer vision and laid the groundwork for my future studies in artificial intelligence.',
    image:'/Projects/2022_matlab_image.png',
    year: 2022,
    technologies: ['Matlab'],
    tags: ['Image Processing', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  {
    title: 'Omnet Simulation',
    description: 'Cool class but never needed to use Omnet again after this.',
    longDescription: 'In this course project, I used Omnet++ to simulate a computer network. I designed and implemented a custom protocol and analyzed its performance under various conditions. While I haven\'t used Omnet++ since, this project provided valuable experience in network simulation and analysis.',
    image:'/Projects/2022_omnet_sim.png',
    year: 2022,
    technologies: ['Omnet++', 'C++'],
    tags: ['Network Simulation', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  {
    title: 'Music Playback Program',
    description: 'Made a rudimentary version of Windows Media Player in C++. The timeline for the project was ultimately cut short.',
    longDescription: 'This was a personal project to build a simple music player in C++. I implemented basic features like playing, pausing, and skipping tracks. Although the project was not completed, it was a great learning experience in object-oriented programming and GUI development with a library like Qt.',
    image:'/Projects/2022_c++_final.png',
    year: 2022,
    technologies: ['C++'],
    tags: ['Desktop App', 'Personal Project'],
    githubLink: '',
    role: 'Developer',
    duration: '',
  },
  {
    title: 'Spotify Analysis Program',
    description: 'Python program that shows the hidden numbers behind any song in the Spotify database - I used this as a foundation in a separate music recommendation app.',
    longDescription: 'This Python script utilizes the Spotify API to fetch and analyze audio features of any given song. It provides insights into metrics like danceability, energy, and valence. I later used this as a backend for a music recommendation app that suggests songs based on a user\'s listening history.',
    image:'/Projects/2022_python_final.png',
    year: 2022,
    technologies: ['Python', 'Spotify API'],
    tags: ['Data Analysis', 'API', 'Personal Project'],
    githubLink: '',
    role: 'Developer',
    duration: '',
  },
  //2021
  {
    title: 'Amplifier with Filters',
    description: 'Did not get to make a physical device in this class at all because of COVID.',
    longDescription: 'This project involved designing an audio amplifier with various filters using simulation software. Due to COVID-19 restrictions, we were unable to build a physical prototype. However, the project provided a solid understanding of analog circuit design and analysis.',
    image:'/Projects/2021_filters.png',
    year: 2021,
    technologies: ['PSpice'],
    tags: ['Circuit Design', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  {
    title: 'Binary Tree Project',
    description: 'Not for the faint of heart (This includes queues, stacks, and lists as well).',
    longDescription: 'This was a comprehensive data structures project where I implemented a binary search tree, along with other fundamental data structures like queues, stacks, and linked lists from scratch in C++. The project honed my problem-solving skills and deepened my understanding of data structures and algorithms.',
    image:'/Projects/2021_binary_tree.png',
    year: 2021,
    technologies: ['C++'],
    tags: ['Data Structures', 'Algorithms', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  //2020
  {
    title: 'Arduino Weather Sensor',
    description: 'Tasked with building a weather-proof weather sensor to leave outside and remotely collect data to measure air quality and make educated weather predictions based on patterns.',
    longDescription: 'In this project, I built a weather sensor using an Arduino and various sensors to collect data on temperature, humidity, and air quality. I also developed a system to remotely access and visualize the data. The goal was to identify patterns in the data to make simple weather predictions.',
    image:'/Projects/2020_arduino.png',
    year: 2020,
    technologies: ['Arduino', 'C++'],
    tags: ['IoT', 'Hardware', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  {
    title: '3D Printed Baby Yoda',
    description: 'The Child',
    longDescription: 'A fun project to learn the basics of 3D modeling and printing. I designed a model of "The Child" (Grogu) from The Mandalorian in a 3D modeling software and printed it using a 3D printer. It was a great introduction to the world of additive manufacturing.',
    image:'/Projects/2020_design.png',
    year: 2020,
    technologies: ['AutoCAD'],
    tags: ['3D Printing', 'Design', 'Personal Project'],
    githubLink: '',
    role: 'Designer',
    duration: '',
  },
  {
    title: 'C++ Artist-Album Analyzer',
    description: 'Used Spotify API to get entire discography of any Spotify-listed artist (precursor to future projects).',
    longDescription: 'This was an early exploration of the Spotify API using C++. The program could fetch the entire discography of a given artist. This project was a precursor to more advanced music analysis and recommendation projects I would undertake later.',
    image:'/Projects/2020_spotify.png',
    year: 2020,
    technologies: ['C++', 'Spotify API'],
    tags: ['API', 'Personal Project'],
    githubLink: '',
    role: 'Developer',
    duration: '',
  },
  //2019
  {
    title: 'Solidworks Drone Design',
    description: 'Graphical engineering class project. Developed a functioning drone schematic in Solidworks.',
    longDescription: 'For my engineering graphics class, I designed a complete drone schematic in Solidworks. This project involved creating individual part models and assembling them into a final product. It was a great exercise in 3D CAD design and mechanical engineering principles.',
    image: '/Projects/2019_drone.png',
    year: 2019,
    technologies: ['Solidworks'],
    tags: ['CAD', 'Design', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  {
    title: 'Robotics Final Project',
    description: 'Tasked with building and configuring an Arduino robot to navigate through a randomized course using inconsistent sensors. It was a test of troublehsooting and patience.',
    longDescription: 'This was the final project for my introductory robotics course. I built and programmed an Arduino-based robot to autonomously navigate a randomized maze. The project was challenging due to the use of noisy and unreliable sensors, which required robust programming and creative problem-solving to overcome.',
    image: '/Projects/2019_robot.jpg',
    year: 2019,
    technologies: ['Arduino', 'C++'],
    tags: ['Robotics', 'Hardware', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  {
    title: 'C++ Final Project',
    description: 'Text-based RPG. Hundreds of lines of story text and a fully developed backend with OOP and base-level reasoning. (Roughly 10 minutes of playtime!).',
    longDescription: 'My final project for my introductory programming course was a text-based RPG written in C++. I focused on creating an engaging story and implementing a solid backend with object-oriented programming principles. The game featured a simple combat system and branching narrative paths.',
    image:'/Projects/2019_final_project.png',
    year: 2019,
    technologies: ['C++'],
    tags: ['Game Dev', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  {
    title: 'Python Final Project',
    description: 'Moderately similar to C++ Project but with developed solo instead.',
    longDescription: 'Similar to my C++ final project, I developed a text-based RPG in Python. This was a solo project, so I had to handle all aspects of development, from story writing to programming the game logic. It was a great opportunity to solidify my understanding of Python and object-oriented design.',
    image:'/Projects/2019_python_project.png',
    year: 2019,
    technologies: ['Python'],
    tags: ['Game Dev', 'Academic'],
    githubLink: '',
    role: 'Student',
    duration: '',
  },
  
  
  
  
  
  

]
